import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Default sidebar for every spoke's plugin-content-docs instance.
 * Docusaurus autogenerates sidebar items from the folder structure, honoring
 * each section's `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
